name: create_plugin

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: "Move files"
      run: |
        mkdir timber-acf-wp-blocks
        shopt -s extglob
        mv timber-acf-wp-blocks.php timber-acf-wp-blocks
